/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPDrawArea.java
 *
 * Created on 01-Feb-2011, 01:27:17
 */

package spirograph;
import java.awt.*;
import java.awt.geom.Ellipse2D;
import javax.swing.*;
/**
 *
 * @author Rhys
 */
public class JPDrawArea extends javax.swing.JPanel {

    /** Creates new form JPDrawArea */
    public JPDrawArea() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void paintComponent(Graphics comp){
        Graphics2D comp2D = (Graphics2D) comp;
        comp2D.setColor(Color.red);
        comp2D.fill(new Ellipse2D.Float(10,10,30,50));

    }
}
