
package projecteuler;

import java.util.ArrayList;
import java.util.List;
/**
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

 * @author Rhys
 */

public class P012_divisors implements Runnable{
//Gets correct answer 76576500 in 1.85s
//Key points: only need to check up to square root, then double for reciprocals
    public void run() {
        long triang = 1;
        int divCount = 0;
        long iter = 2;

        while (divCount <= 500){
            divCount = 1; //itself
            triang = getTriang(iter);
            for (int i = 1; i <= triang / i; i++) {
                if (triang % i == 0){
                    divCount++;
                }
            }
            divCount = divCount * 2; // account for reciprocals
            iter++;
        }
        System.out.println(triang + " has " + divCount + " divisors.");
    }

    long getTriang(long n){
        return n*(n+1)/2;
    }

}
